// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlxmM-_Tbn9hQutC_49S2mzAxQMIkuqMU',
    appId: '1:1019417478911:web:0e14a623206e9df90b2eca',
    messagingSenderId: '1019417478911',
    projectId: 'eco-fit-31164',
    authDomain: 'eco-fit-31164.firebaseapp.com',
    storageBucket: 'eco-fit-31164.appspot.com',
    measurementId: 'G-4YJ49QF88P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7E6uSXFwJQyk4ZiniKOZOsGgMyyhj1U',
    appId: '1:1019417478911:android:0d0d8b2d5149294d0b2eca',
    messagingSenderId: '1019417478911',
    projectId: 'eco-fit-31164',
    storageBucket: 'eco-fit-31164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCogJOvflcCtkaN71eqU_a-BU-E2CF6jps',
    appId: '1:1019417478911:ios:77f3044e0e2f63ea0b2eca',
    messagingSenderId: '1019417478911',
    projectId: 'eco-fit-31164',
    storageBucket: 'eco-fit-31164.appspot.com',
    iosClientId: '1019417478911-ukpt35a0j0e3i8a7kogf48kjt7ahnc06.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoFit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCogJOvflcCtkaN71eqU_a-BU-E2CF6jps',
    appId: '1:1019417478911:ios:77f3044e0e2f63ea0b2eca',
    messagingSenderId: '1019417478911',
    projectId: 'eco-fit-31164',
    storageBucket: 'eco-fit-31164.appspot.com',
    iosClientId: '1019417478911-ukpt35a0j0e3i8a7kogf48kjt7ahnc06.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecoFit',
  );
}
